feat: local tests.

diff --git a/scripts/monza/faucet b/scripts/monza/faucet
--- a/scripts/monza/faucet
+++ b/scripts/monza/faucet
@@ -1,6 +1,19 @@
 #!/bin/bash -e
-# Change directory to the one specified in the environment variable
-cd "$MONZA_APTOS_PATH" # this should be provided by nix
+
+# Setup a trap to clean up the temporary directory on EXIT
+cleanup() {
+    echo "Cleaning up temporary directory."
+    rm -rf "$temp_dir"
+}
+trap cleanup EXIT
+
+# Copy the directory from the Nix store to a temporary location
+temp_dir=$MOVEMENT_BASE_STORAGE_PATH/monza-aptos
+cp -R "$MONZA_APTOS_PATH" "$temp_dir"
+chmod -R 755 $temp_dir
+
+# Change to the temporary directory
+cd "$temp_dir"
 
 # Split the listen addresses into an array
 IFS=':' read -r -a listener_array <<< "$MONZA_APTOS_FAUCET_LISTEN_ADDR"
@@ -9,6 +22,14 @@ IFS=':' read -r -a listener_array <<< "$MONZA_APTOS_FAUCET_LISTEN_ADDR"
 LISTEN_ADDR="${listener_array[0]}"
 LISTEN_PORT="${listener_array[1]}"
 
+echo "Starting faucet service with the following configuration:"
+echo "  - Chain ID: $MONZA_CHAIN_ID"
+echo "  - Node URL: $MONZA_APTOS_REST_LISTEN_ADDR"
+echo "  - Faucet URL: $MONZA_APTOS_FAUCET_LISTEN_ADDR"
+
 # Run the faucet service using cargo
-cargo run -p aptos-faucet-service -- run-simple --key "$MONZA_PRIVATE_KEY" \
-    --node-url "http://$MONZA_APTOS_REST_LISTEN_ADDR" --chain-id "$MONZA_CHAIN_ID"
+cargo run -p aptos-faucet-service -- run-simple --key "$MONZA_APTOS_PRIVATE_KEY" \
+    --node-url "http://$MONZA_APTOS_REST_LISTEN_ADDR" --chain-id "$MONZA_CHAIN_ID" \
+    --listen-address "$LISTEN_ADDR" --listen-port "$LISTEN_PORT"
+
+# The script automatically calls cleanup when it exits due to the trap
