remove old archive file and define docker file for backup follower

diff --git a/docker/compose/movement-full-node/docker-compose.follower.backup.yaml b/docker/compose/movement-full-node/docker-compose.follower.backup.yaml
--- a/docker/compose/movement-full-node/docker-compose.follower.backup.yaml
+++ b/docker/compose/movement-full-node/docker-compose.follower.backup.yaml
@@ -87,20 +87,16 @@ services:
       - MOVEMENT_TIMING=info
       - SUZUKA_TIMING_LOG=/.movement/movement-timing.log
       - RUST_BACKTRACE=1
-      - SYNC_PATTERN="{maptos,maptos-storage,suzuka-da-db}/**"
-      - SYNC_BUCKET="mtnet-l-sync-bucket-sync"
-      - SYNC_ARCHIVE="0.tar.gz"
+      - SYNC_PATTERN=${SYNC_PATTERN}
+      - SYNC_BUCKET=${SYNC_BUCKET}
+      - SYNC_ARCHIVE=${SYNC_ARCHIVE}
     entrypoint: /bin/sh
     command: |
       sh -c '
-        rm -rf /.movement-snapshot
-        cp -r /.movement /.movement-snapshot
-        export DOT_MOVEMENT_PATH=/.movement-snapshot
         while true; do
-          echo "Running movement-full-node for 60 seconds..."
           timeout 60s movement-full-node run || echo "Node run timed out"
           echo "Taking snapshot..."
-          movement-full-node backup push || echo "Snapshot failed"
+          movement-full-node backup save-and-push $SYNC_BUCKET $SYNC_PATTERN $SYNC_ARCHIVE || echo "Snapshot failed"
         done
       '
     volumes:
